### PR TITLE
feat: Add ExposeAccessTokenToFrontendInCookieBasedAuth (JWT Rework #6)

### PR DESCRIPTION
**Pull request by nkshah2**
## Summary of change

- Adds `ExposeAccessTokenToFrontendInCookieBasedAuth` to the session recipe and handles it when setting access token in the response
- Adds `checkDatabase` as a param for verify and get session

## Checklist for important updates

-   [x] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens/constants.go`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `supertokens/constants.go > version variable`
-   [x] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR

-   [ ] ...

### CODE REVIEW

**Review by porcellus — CHANGES_REQUESTED** [review]
Missed some TODOs in `sessionFunctions.go` (see comments in the #4 PR: [recipe/session/sessionFunctions.go](https://github.com/supertokens/supertokens-golang/pull/262/files/66a6797c3e28e4bcfa2913e961a928eb3ae2aa7d#diff-0ad6bec0af95960515575cdc8ad0b462f6faef1eb21429a5a14b4b5061c320f6))

**Comment by nkshah2** [comment]
> Missed some TODOs in `sessionFunctions.go` (see comments in the #4 PR: [recipe/session/sessionFunctions.go](https://github.com/supertokens/supertokens-golang/pull/262/files/66a6797c3e28e4bcfa2913e961a928eb3ae2aa7d#diff-0ad6bec0af95960515575cdc8ad0b462f6faef1eb21429a5a14b4b5061c320f6))

This is actually fixed in this PR in the block after where this comment is:

```go
requestBody := map[string]interface{}{
    "accessToken":     parsedAccessToken.RawTokenString,
    "doAntiCsrfCheck": doAntiCsrfCheck,
    "enableAntiCsrf":  config.AntiCsrf == antiCSRF_VIA_TOKEN,
    "checkDatabase":   alwaysCheckCore,
}
```

I removed the TODO in PR #7 (https://github.com/supertokens/supertokens-golang/pull/265) because I forgot to do it in this one and didnt fix it to avoid a conflict

**Review by porcellus — CHANGES_REQUESTED** [review]
The TODO comment was removed there, but it wasn't actually fixed... The if statement after the comment is supposed to take `alwaysCheckCore` into account.

**Comment by nkshah2** [comment]
> The TODO comment was removed there, but it wasn't actually fixed... The if statement after the comment is supposed to take `alwaysCheckCore` into account.

Ah right I missed that. Fixed

**Review by porcellus — APPROVED** [review]
LGTM. Waiting with merge until #263 is merged

**Pull request merged**
