### PR TITLE
fix: Merge emailpassword formFields loops

### PR DESCRIPTION
**Pull request by wallstromsimon**
## Summary of change
Use the same loop to extract both email and password from formFields.

## Related issues
https://github.com/supertokens/supertokens-golang/issues/220

## Test Plan
Running locally, according to https://github.com/supertokens/supertokens-golang/blob/master/CONTRIBUTING.md#testing 

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `coreDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `supertokens/constants.go`
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `supertokens/constants.go > version variable`
-   [ ] Had installed and ran the pre-commit hook
-   [x] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.

### CODE REVIEW

**Comment by wallstromsimon** [comment]
My first PR in this project, let me know if I missed something. I'm not 100% confident in the versioning / base branch, if there's any pointers I'm happy to fix that :)

**Review by rishabhpoddar — APPROVED** [review]

**Comment by rishabhpoddar** [comment]
hey @wallstromsimon thanks for this PR. Can you please update the changelog under the `[unreleased]` section please?

**Comment by rishabhpoddar** [comment]
This will get released in the next feature update :) Thanks

**Comment by rishabhpoddar** [comment]
I have also added your profile on the [supertokens-core readme](https://github.com/supertokens/supertokens-core) :)

**Comment by wallstromsimon** [comment]
Awesome, thanks! Do you want me to open a new pr to fix the changelog? :D

**Pull request merged**
